[package]
name = "pochita"
version = "0.1.0"
edition = "2021"
description = "Arena allocator."
license = "MIT/Apache-2.0"
repository = "https://github.com/nikoraefu/pochita"
categories = ["memory-management"]
keywords = ["arena"]

[dependencies]
sptr = "0.3"
