name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings -W unreachable-pub"
  RUST_BACKTRACE: short

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    
    - name: Install Rust toolchain
      run: |
          rustup update --no-self-update nightly
          rustup component add rustfmt clippy
          
    - name: Build
      run: cargo build
    
    - name: Run tests
      run: cargo test
    
    - name: Run clippy
      run: cargo clippy
      
    - name: Run fmt
      run: cargo fmt --check
